# Generated by Django 5.1.6 on 2025-02-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_pet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
    ]
