# Generated by Django 5.1.6 on 2025-02-22 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_doorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWaterLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('food', 'Food'), ('water', 'Water')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_water_logs', to='dashboard.pet')),
            ],
        ),
    ]
