# Generated by Django 5.1.6 on 2025-02-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_foodlog_quantity_alter_waterlog_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlog',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=50),
        ),
        migrations.AlterField(
            model_name='doorlog',
            name='direction',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=50),
        ),
        migrations.AlterField(
            model_name='doorlog',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_logs', to='dashboard.pet'),
        ),
        migrations.AlterField(
            model_name='doorlog',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='close', max_length=50),
        ),
    ]
