# Generated by Django 5.1.6 on 2025-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_locationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='automatic_food_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='automatic_food_mode',
            field=models.CharField(choices=[('timed', 'Timed'), ('interval', 'Interval')], default='timed', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='automatic_food_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='automatic_food_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='automatic_water_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='automatic_water_mode',
            field=models.CharField(choices=[('timed', 'Timed'), ('interval', 'Interval')], default='timed', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='automatic_water_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='automatic_water_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='food_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='water_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=50),
        ),
    ]
