# Generated by Django 5.1.6 on 2025-02-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_pet_automatic_food_interval_pet_automatic_food_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='allow_in_after_closing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='always_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='door_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='door_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='in_house',
            field=models.BooleanField(default=True),
        ),
    ]
