# Generated by Django 5.1.6 on 2025-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_pet_allow_in_after_closing_pet_always_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='door_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=50),
        ),
    ]
