# Generated by Django 5.1.6 on 2025-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_pet_door_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('parrot', 'Parrot'), ('hamster', 'Hamster'), ('fish', 'Fish'), ('dragon', 'Dragon'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
