# Generated by Django 5.1.6 on 2025-02-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_pet_age_alter_pet_type_alter_waterlog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='dob',
            field=models.DateField(default=None, null=True),
        ),
    ]
