# Generated by Django 5.1.6 on 2025-02-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_pet_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='exact_birthday',
            field=models.BooleanField(default=False),
        ),
    ]
